apiVersion: v1
kind: Pod
metadata:
  name: purple
spec:
  initContainers:
  - command:
    - sh
    - -c
    - sleep 10
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: warm-up-1
  - command:
    - sh
    - -c
    - sleep 10
    image: busybox:1.28
    name: warm-up-2
  containers:
    - command:
      - sh
      - -c
      - echo The app is running! && sleep 3600
      image: busybox:1.28
      name: purple-container