apiVersion: v1
kind: Service
metadata:
  name: sample-webapp-service
  labels:
    name: sample-webapp
spec:
  selector:
    name: sample-webapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32125