apiVersion: v1
kind: Pod
metadata:
  name: annotated-pod
  annotations:
    commit: 845er5
    author: "Aravind"
    branch: "feature/annotations"
spec:
  containers:
    - name: nginx
      image: nginx