apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    name: votingapp
    tier: front-end
spec:
  type: NodePort
  selector:
    name: votingapp
    tier: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32345