apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redisapp
    tier: middle
spec:
  type: ClusterIP
  selector: #Service Selector
    name: redisapp
    tier: middle
  ports:
    - port: 6379
      targetPort: 6379