apiVersion: v1
kind: Pod
metadata:
  name: request-pod
spec:
  containers:
    - name: cpu-stress
      image: ubuntu
      args:
      - sleep
      - "100"
      resources:
        limits:
          cpu: "2"
        requests:
          cpu: "1"