apiVersion: v1
kind: Service
metadata:
  name: req-service
  labels:
    app: req-limits
spec:
  type: NodePort
  selector:
    app: req-limits
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31234