apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: backend-application
    tier: backend
  namespace: training
spec:
  selector:
    app: backend-application
  ports:
    - name: http
      port: 8080
      targetPort: 8080