apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-application
    tier: frontend
  namespace: training
spec:
  type: NodePort
  selector: 
    app: frontend-application
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32128