apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgre-service
    tier: middle
spec:
  selector:
    name: postgresapp
    tier: middle
  ports:
    - port: 5432
      targetPort: 5432