apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: c3FsZGIwMQ== # required field for kubernetes.io/basic-auth
  password: c3FsYWRtaW4=